name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: hseeberger/scala-sbt
    steps:
    - uses: actions/checkout@v1
    - name: Run tests in sbt
      run: sbt tests/run
